# Generated by Django 2.2.4 on 2019-08-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='lm_id',
            field=models.CharField(default='000', max_length=100),
        ),
    ]
