# Generated by Django 2.2.4 on 2019-08-12 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_auto_20190812_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='_id',
            new_name='emp_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='_lm_id',
            new_name='lm_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='_name',
            new_name='name',
        ),
    ]
